# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-02-18 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20170112_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Started follow'), (1, 'Mentioned in comment'), (2, 'Votes reached'), (3, 'Ending soon: owner'), (4, 'Ending soon: pinner'), (5, 'Ending soon: upvoter'), (6, 'Ending soon: downvoter'), (7, 'Shared a Blast'), (8, 'Shared a hashtag'), (9, 'Commented post'), (10, 'Marked for removal'), (11, 'Replied on comment'), (12, 'set the selt destruct to 24hrs'), (13, 'changed the group name to {}.'), (14, '{} took a screenshot')]),
        ),
    ]
