# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-12 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20170112_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
