# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-13 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20170112_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cap_rotate_ang',
            field=models.FloatField(null=True, verbose_name='Caption Rotation Angle'),
        ),
        migrations.AddField(
            model_name='post',
            name='caption_height',
            field=models.FloatField(null=True, verbose_name='Caption Height'),
        ),
        migrations.AddField(
            model_name='post',
            name='caption_width',
            field=models.FloatField(null=True, verbose_name='Caption Width'),
        ),
        migrations.AddField(
            model_name='post',
            name='caption_x_pos',
            field=models.FloatField(null=True, verbose_name='Caption Center X Position'),
        ),
        migrations.AddField(
            model_name='post',
            name='caption_y_pos',
            field=models.FloatField(null=True, verbose_name='Caption Center Y Position'),
        ),
        migrations.AddField(
            model_name='post',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Location Latitude'),
        ),
        migrations.AddField(
            model_name='post',
            name='location_name',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='lon',
            field=models.FloatField(blank=True, null=True, verbose_name='Location Longitude'),
        ),
        migrations.AddField(
            model_name='post',
            name='media_height',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='media_width',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
