# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-13 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20170113_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cap_rotate_ang',
            field=models.FloatField(default=0, verbose_name='Caption Rotation Angle'),
        ),
        migrations.AlterField(
            model_name='post',
            name='caption_height',
            field=models.FloatField(default=0, verbose_name='Caption Height'),
        ),
        migrations.AlterField(
            model_name='post',
            name='caption_width',
            field=models.FloatField(default=0, verbose_name='Caption Width'),
        ),
        migrations.AlterField(
            model_name='post',
            name='caption_x_pos',
            field=models.FloatField(default=0, verbose_name='Caption Center X Position'),
        ),
        migrations.AlterField(
            model_name='post',
            name='caption_y_pos',
            field=models.FloatField(default=0, verbose_name='Caption Center Y Position'),
        ),
    ]
