# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-12 16:20
from __future__ import unicode_literals

from django.db import migrations, models
import smsconfirmation.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneConfirmation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(max_length=20)),
                ('code', models.CharField(default=smsconfirmation.models.get_phone_confirmation_code, max_length=4)),
                ('is_delivered', models.BooleanField(default=False)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('request_type', models.IntegerField(choices=[(1, 'Phone confirmation'), (2, 'Reset password')])),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
