# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-03-18 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import smsconfirmation.models


class Migration(migrations.Migration):

    dependencies = [
        ('smsconfirmation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendSms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(max_length=20)),
                ('code', models.CharField(default=smsconfirmation.models.get_phone_confirmation_code, max_length=4)),
            ],
        ),
    ]
