# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-03-20 11:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smsconfirmation', '0002_sendsms'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SendSms',
            new_name='VerifyCreate',
        ),
    ]
