# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-03-20 11:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smsconfirmation', '0003_auto_20180320_1132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verifycreate',
            old_name='phone',
            new_name='recipient',
        ),
    ]
